spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: banking_user
      POSTGRES_PASSWORD: banking_pass
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    flyway:
      enabled: true